// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicField: typeof import('./../layouts/basic-layout/components/field-panel/BasicField.vue')['default']
    BasicFields: typeof import('./../layouts/basic-layout/components/field-panel/basic-fields/index.vue')['default']
    BasicLayout: typeof import('./../layouts/basic-layout/index.vue')['default']
    BasicLayoutHeader: typeof import('./../layouts/basic-layout/components/BasicLayoutHeader.vue')['default']
    BasicSettings: typeof import('./../layouts/basic-layout/components/setting-panel/BasicSettings.vue')['default']
    ContainField: typeof import('./../layouts/basic-layout/components/field-panel/contain-field.vue')['default']
    ContainFields: typeof import('./../layouts/basic-layout/components/field-panel/contain-fields/index.vue')['default']
    Drawer: typeof import('./../layouts/basic-layout/components/drawer-panel/Drawer.vue')['default']
    DrawerGrid: typeof import('./../layouts/basic-layout/components/drawer-panel/drawerGrid/drawerGrid.vue')['default']
    DrawerPanel: typeof import('./../layouts/basic-layout/components/drawer-panel/index.vue')['default']
    DrawerPanelHeader: typeof import('./../layouts/basic-layout/components/drawer-panel/drawerPanelHeader/DrawerPanelHeader.vue')['default']
    FieldItem: typeof import('./../layouts/basic-layout/components/field-panel/FieldItem.vue')['default']
    FieldPanel: typeof import('./../layouts/basic-layout/components/field-panel/index.vue')['default']
    InputAttribute: typeof import('./../layouts/basic-layout/components/setting-panel/components/inputAttribute.vue')['default']
    ItemWrapper: typeof import('./../layouts/basic-layout/components/drawer-panel/ItemWrapper.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NModal: typeof import('naive-ui')['NModal']
    NSlider: typeof import('naive-ui')['NSlider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTab: typeof import('naive-ui')['NTab']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    PanelHeaderModal: typeof import('./../layouts/basic-layout/components/drawer-panel/drawerPanelHeader/panelHeaderModal.vue')['default']
    Setting: typeof import('./../layouts/basic-layout/components/setting-panel/components/setting.vue')['default']
    SettingPanel: typeof import('./../layouts/basic-layout/components/setting-panel/index.vue')['default']
    SettingPart: typeof import('./../layouts/basic-layout/components/setting-panel/components/settingPart.vue')['default']
    SettingsForm: typeof import('./../layouts/basic-layout/components/setting-panel/SettingsForm.vue')['default']
    SliderAttribute: typeof import('./../layouts/basic-layout/components/setting-panel/components/sliderAttribute.vue')['default']
    StyleSettings: typeof import('./../layouts/basic-layout/components/setting-panel/styleSettings.vue')['default']
    VueJsonEditor: typeof import('./../layouts/basic-layout/components/drawer-panel/drawerPanelHeader/vueJsonEditor.vue')['default']
  }
}
