// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicField: typeof import('./../layouts/basic-layout/components/field-panel/BasicField.vue')['default']
    BasicLayout: typeof import('./../layouts/basic-layout/index.vue')['default']
    BasicLayoutHeader: typeof import('./../layouts/basic-layout/components/BasicLayoutHeader.vue')['default']
    Drawer: typeof import('./../layouts/basic-layout/components/drawer-panel/Drawer.vue')['default']
    DrawerPanel: typeof import('./../layouts/basic-layout/components/drawer-panel/index.vue')['default']
    DrawerPanelHeader: typeof import('./../layouts/basic-layout/components/drawer-panel/DrawerPanelHeader.vue')['default']
    FieldItem: typeof import('./../layouts/basic-layout/components/field-panel/FieldItem.vue')['default']
    FieldPanel: typeof import('./../layouts/basic-layout/components/field-panel/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NTag: typeof import('naive-ui')['NTag']
    SettingPanel: typeof import('./../layouts/basic-layout/components/setting-panel/index.vue')['default']
  }
}
